DROP TABLE IF EXISTS DEPARTMENT;

CREATE TABLE DEPARTMENT (
  DEPARTMENT_ID INT NOT NULL AUTO_INCREMENT,
  DEPARTMENT_NAME VARCHAR(20) NOT NULL UNIQUE,
  PRIMARY KEY (DEPARTMENT_ID)
);

DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE (
  EMPLOYEE_ID INT NOT NULL AUTO_INCREMENT,
  FIRSTNAME VARCHAR(255) NOT NULL,
  LASTNAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL UNIQUE,
  SALARY INT NOT NULL,
  DEPARTMENT_ID INT NOT NULL,
  PRIMARY KEY (EMPLOYEE_ID),
  FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);